/*
 * ctrl_fifos.c
 *
 *  Created on: 22 janv. 2015
 *      Author: yolivave
 */

#include "config.h"
#include "ctrl_fifo_functions.h"
#include "ctrl_fifos.h"


//--- Control FIFOs macros
//  µB 0
#define CTRL_FIFO_OUT_0_SIZE 		1024
#define CTRL_FIFO_OUT_0_START_ADDR	0x40040000
#define CTRL_FIFO_OUT_0_RD_IX_ADDR	CTRL_FIFO_OUT_0_START_ADDR + CTRL_FIFO_OUT_0_SIZE
#define CTRL_FIFO_OUT_0_WR_IX_ADDR	CTRL_FIFO_OUT_0_RD_IX_ADDR + 4
#define CTRL_FIFO_OUT_0_END_ADDR	CTRL_FIFO_OUT_0_WR_IX_ADDR + 4

#define CTRL_FIFO_IN_0_SIZE			1024
#define CTRL_FIFO_IN_0_START_ADDR	0x40040408
#define CTRL_FIFO_IN_0_RD_IX_ADDR	CTRL_FIFO_IN_0_START_ADDR + CTRL_FIFO_IN_0_SIZE
#define CTRL_FIFO_IN_0_WR_IX_ADDR	CTRL_FIFO_IN_0_RD_IX_ADDR + 4
#define CTRL_FIFO_IN_0_END_ADDR		CTRL_FIFO_IN_0_WR_IX_ADDR + 4

#define INPUT_FILE_SIZE			250344 // 0x3D1E8 Size of the encoded input file.
#define INPUT_FILE_START_ADDR	0x40040a00
#define INPUT_FILE_RD_IX_ADDR	INPUT_FILE_START_ADDR + INPUT_FILE_SIZE
#define INPUT_FILE_WR_IX_ADDR	INPUT_FILE_RD_IX_ADDR + 4

// µB 1
#define CTRL_FIFO_OUT_1_SIZE 		1024
#define CTRL_FIFO_OUT_1_START_ADDR	0x40002000
#define CTRL_FIFO_OUT_1_RD_IX_ADDR	CTRL_FIFO_OUT_1_START_ADDR + CTRL_FIFO_OUT_1_SIZE
#define CTRL_FIFO_OUT_1_WR_IX_ADDR	CTRL_FIFO_OUT_1_RD_IX_ADDR + 4
#define CTRL_FIFO_OUT_1_END_ADDR	CTRL_FIFO_OUT_1_WR_IX_ADDR + 4

#define CTRL_FIFO_IN_1_SIZE			1024
#define CTRL_FIFO_IN_1_START_ADDR	0x40002408
#define CTRL_FIFO_IN_1_RD_IX_ADDR	CTRL_FIFO_IN_1_START_ADDR + CTRL_FIFO_IN_1_SIZE
#define CTRL_FIFO_IN_1_WR_IX_ADDR	CTRL_FIFO_IN_1_RD_IX_ADDR + 4
#define CTRL_FIFO_IN_1_END_ADDR		CTRL_FIFO_IN_1_WR_IX_ADDR + 4


// µB 2
#define CTRL_FIFO_OUT_2_SIZE 		1024
#define CTRL_FIFO_OUT_2_START_ADDR	0x40004000
#define CTRL_FIFO_OUT_2_RD_IX_ADDR	CTRL_FIFO_OUT_2_START_ADDR + CTRL_FIFO_OUT_2_SIZE
#define CTRL_FIFO_OUT_2_WR_IX_ADDR	CTRL_FIFO_OUT_2_RD_IX_ADDR + 4
#define CTRL_FIFO_OUT_2_END_ADDR	CTRL_FIFO_OUT_2_WR_IX_ADDR + 4

#define CTRL_FIFO_IN_2_SIZE			1024
#define CTRL_FIFO_IN_2_START_ADDR	0x40004408
#define CTRL_FIFO_IN_2_RD_IX_ADDR	CTRL_FIFO_IN_2_START_ADDR + CTRL_FIFO_IN_2_SIZE
#define CTRL_FIFO_IN_2_WR_IX_ADDR	CTRL_FIFO_IN_2_RD_IX_ADDR + 4
#define CTRL_FIFO_IN_2_END_ADDR		CTRL_FIFO_IN_2_WR_IX_ADDR + 4


// µB 3
#define CTRL_FIFO_OUT_3_SIZE 		1024
#define CTRL_FIFO_OUT_3_START_ADDR	0x40006000
#define CTRL_FIFO_OUT_3_RD_IX_ADDR	CTRL_FIFO_OUT_3_START_ADDR + CTRL_FIFO_OUT_3_SIZE
#define CTRL_FIFO_OUT_3_WR_IX_ADDR	CTRL_FIFO_OUT_3_RD_IX_ADDR + 4
#define CTRL_FIFO_OUT_3_END_ADDR	CTRL_FIFO_OUT_3_WR_IX_ADDR + 4

#define CTRL_FIFO_IN_3_SIZE			1024
#define CTRL_FIFO_IN_3_START_ADDR	0x40006408
#define CTRL_FIFO_IN_3_RD_IX_ADDR	CTRL_FIFO_IN_3_START_ADDR + CTRL_FIFO_IN_3_SIZE
#define CTRL_FIFO_IN_3_WR_IX_ADDR	CTRL_FIFO_IN_3_RD_IX_ADDR + 4
#define CTRL_FIFO_IN_3_END_ADDR		CTRL_FIFO_IN_3_WR_IX_ADDR + 4


// µB 4
#define CTRL_FIFO_OUT_4_SIZE 		1024
#define CTRL_FIFO_OUT_4_START_ADDR	0x40008000
#define CTRL_FIFO_OUT_4_RD_IX_ADDR	CTRL_FIFO_OUT_4_START_ADDR + CTRL_FIFO_OUT_4_SIZE
#define CTRL_FIFO_OUT_4_WR_IX_ADDR	CTRL_FIFO_OUT_4_RD_IX_ADDR + 4
#define CTRL_FIFO_OUT_4_END_ADDR	CTRL_FIFO_OUT_4_WR_IX_ADDR + 4

#define CTRL_FIFO_IN_4_SIZE			1024
#define CTRL_FIFO_IN_4_START_ADDR	0x40008408
#define CTRL_FIFO_IN_4_RD_IX_ADDR	CTRL_FIFO_IN_4_START_ADDR + CTRL_FIFO_IN_4_SIZE
#define CTRL_FIFO_IN_4_WR_IX_ADDR	CTRL_FIFO_IN_4_RD_IX_ADDR + 4
#define CTRL_FIFO_IN_4_END_ADDR		CTRL_FIFO_IN_4_WR_IX_ADDR + 4


// µB 5
#define CTRL_FIFO_OUT_5_SIZE 		1024
#define CTRL_FIFO_OUT_5_START_ADDR	0x4000a000
#define CTRL_FIFO_OUT_5_RD_IX_ADDR	CTRL_FIFO_OUT_5_START_ADDR + CTRL_FIFO_OUT_5_SIZE
#define CTRL_FIFO_OUT_5_WR_IX_ADDR	CTRL_FIFO_OUT_5_RD_IX_ADDR + 4
#define CTRL_FIFO_OUT_5_END_ADDR	CTRL_FIFO_OUT_5_WR_IX_ADDR + 4

#define CTRL_FIFO_IN_5_SIZE 		1024
#define CTRL_FIFO_IN_5_START_ADDR	0x4000a408
#define CTRL_FIFO_IN_5_RD_IX_ADDR	CTRL_FIFO_IN_5_START_ADDR + CTRL_FIFO_IN_5_SIZE
#define CTRL_FIFO_IN_5_WR_IX_ADDR	CTRL_FIFO_IN_5_RD_IX_ADDR + 4
#define CTRL_FIFO_IN_5_END_ADDR		CTRL_FIFO_IN_5_WR_IX_ADDR + 4


// µB 6
#define CTRL_FIFO_OUT_6_SIZE 		1024
#define CTRL_FIFO_OUT_6_START_ADDR	0x4000c000
#define CTRL_FIFO_OUT_6_RD_IX_ADDR	CTRL_FIFO_OUT_6_START_ADDR + CTRL_FIFO_OUT_6_SIZE
#define CTRL_FIFO_OUT_6_WR_IX_ADDR	CTRL_FIFO_OUT_6_RD_IX_ADDR + 4
#define CTRL_FIFO_OUT_6_END_ADDR	CTRL_FIFO_OUT_6_WR_IX_ADDR + 4

#define CTRL_FIFO_IN_6_SIZE 		1024
#define CTRL_FIFO_IN_6_START_ADDR	0x4000c408
#define CTRL_FIFO_IN_6_RD_IX_ADDR	CTRL_FIFO_IN_6_START_ADDR + CTRL_FIFO_IN_6_SIZE
#define CTRL_FIFO_IN_6_WR_IX_ADDR	CTRL_FIFO_IN_6_RD_IX_ADDR + 4
#define CTRL_FIFO_IN_6_END_ADDR		CTRL_FIFO_IN_6_WR_IX_ADDR + 4


// µB 7
#define CTRL_FIFO_OUT_7_SIZE 		1024
#define CTRL_FIFO_OUT_7_START_ADDR	0x4000e000
#define CTRL_FIFO_OUT_7_RD_IX_ADDR	CTRL_FIFO_OUT_7_START_ADDR + CTRL_FIFO_OUT_7_SIZE
#define CTRL_FIFO_OUT_7_WR_IX_ADDR	CTRL_FIFO_OUT_7_RD_IX_ADDR + 4
#define CTRL_FIFO_OUT_7_END_ADDR	CTRL_FIFO_OUT_7_WR_IX_ADDR + 4

#define CTRL_FIFO_IN_7_SIZE 		1024
#define CTRL_FIFO_IN_7_START_ADDR	0x4000e408
#define CTRL_FIFO_IN_7_RD_IX_ADDR	CTRL_FIFO_IN_7_START_ADDR + CTRL_FIFO_IN_7_SIZE
#define CTRL_FIFO_IN_7_WR_IX_ADDR	CTRL_FIFO_IN_7_RD_IX_ADDR + 4
#define CTRL_FIFO_IN_7_END_ADDR		CTRL_FIFO_IN_7_WR_IX_ADDR + 4


// µB 8
#define CTRL_FIFO_OUT_8_SIZE 		1024
#define CTRL_FIFO_OUT_8_START_ADDR	0x40010000
#define CTRL_FIFO_OUT_8_RD_IX_ADDR	CTRL_FIFO_OUT_8_START_ADDR + CTRL_FIFO_OUT_8_SIZE
#define CTRL_FIFO_OUT_8_WR_IX_ADDR	CTRL_FIFO_OUT_8_RD_IX_ADDR + 4
#define CTRL_FIFO_OUT_8_END_ADDR	CTRL_FIFO_OUT_8_WR_IX_ADDR + 4

#define CTRL_FIFO_IN_8_SIZE 		1024
#define CTRL_FIFO_IN_8_START_ADDR	0x40010408
#define CTRL_FIFO_IN_8_RD_IX_ADDR	CTRL_FIFO_IN_8_START_ADDR + CTRL_FIFO_IN_8_SIZE
#define CTRL_FIFO_IN_8_WR_IX_ADDR	CTRL_FIFO_IN_8_RD_IX_ADDR + 4
#define CTRL_FIFO_IN_8_END_ADDR		CTRL_FIFO_IN_8_WR_IX_ADDR + 4


// µB 9
#define CTRL_FIFO_OUT_9_SIZE 		1024
#define CTRL_FIFO_OUT_9_START_ADDR	0x40012000
#define CTRL_FIFO_OUT_9_RD_IX_ADDR	CTRL_FIFO_OUT_9_START_ADDR + CTRL_FIFO_OUT_9_SIZE
#define CTRL_FIFO_OUT_9_WR_IX_ADDR	CTRL_FIFO_OUT_9_RD_IX_ADDR + 4
#define CTRL_FIFO_OUT_9_END_ADDR	CTRL_FIFO_OUT_9_WR_IX_ADDR + 4

#define CTRL_FIFO_IN_9_SIZE 		1024
#define CTRL_FIFO_IN_9_START_ADDR	0x40012408
#define CTRL_FIFO_IN_9_RD_IX_ADDR	CTRL_FIFO_IN_9_START_ADDR + CTRL_FIFO_IN_9_SIZE
#define CTRL_FIFO_IN_9_WR_IX_ADDR	CTRL_FIFO_IN_9_RD_IX_ADDR + 4
#define CTRL_FIFO_IN_9_END_ADDR		CTRL_FIFO_IN_9_WR_IX_ADDR + 4


// µB 10
#define CTRL_FIFO_OUT_10_SIZE 		1024
#define CTRL_FIFO_OUT_10_START_ADDR	0x40014000
#define CTRL_FIFO_OUT_10_RD_IX_ADDR	CTRL_FIFO_OUT_10_START_ADDR + CTRL_FIFO_OUT_10_SIZE
#define CTRL_FIFO_OUT_10_WR_IX_ADDR	CTRL_FIFO_OUT_10_RD_IX_ADDR + 4
#define CTRL_FIFO_OUT_10_END_ADDR	CTRL_FIFO_OUT_10_WR_IX_ADDR + 4

#define CTRL_FIFO_IN_10_SIZE 		1024
#define CTRL_FIFO_IN_10_START_ADDR	0x40014408
#define CTRL_FIFO_IN_10_RD_IX_ADDR	CTRL_FIFO_IN_10_START_ADDR + CTRL_FIFO_IN_10_SIZE
#define CTRL_FIFO_IN_10_WR_IX_ADDR	CTRL_FIFO_IN_10_RD_IX_ADDR + 4
#define CTRL_FIFO_IN_10_END_ADDR	CTRL_FIFO_IN_10_WR_IX_ADDR + 4


// µB 11
#define CTRL_FIFO_OUT_11_SIZE 		1024
#define CTRL_FIFO_OUT_11_START_ADDR	0x40016000
#define CTRL_FIFO_OUT_11_RD_IX_ADDR	CTRL_FIFO_OUT_11_START_ADDR + CTRL_FIFO_OUT_11_SIZE
#define CTRL_FIFO_OUT_11_WR_IX_ADDR	CTRL_FIFO_OUT_11_RD_IX_ADDR + 4
#define CTRL_FIFO_OUT_11_END_ADDR	CTRL_FIFO_OUT_11_WR_IX_ADDR + 4

#define CTRL_FIFO_IN_11_SIZE 		1024
#define CTRL_FIFO_IN_11_START_ADDR	0x40016408
#define CTRL_FIFO_IN_11_RD_IX_ADDR	CTRL_FIFO_IN_11_START_ADDR + CTRL_FIFO_IN_11_SIZE
#define CTRL_FIFO_IN_11_WR_IX_ADDR	CTRL_FIFO_IN_11_RD_IX_ADDR + 4
#define CTRL_FIFO_IN_11_END_ADDR		CTRL_FIFO_IN_11_WR_IX_ADDR + 4


// µB 12
#define CTRL_FIFO_OUT_12_SIZE 		1024
#define CTRL_FIFO_OUT_12_START_ADDR	0x40018000
#define CTRL_FIFO_OUT_12_RD_IX_ADDR	CTRL_FIFO_OUT_12_START_ADDR + CTRL_FIFO_OUT_12_SIZE
#define CTRL_FIFO_OUT_12_WR_IX_ADDR	CTRL_FIFO_OUT_12_RD_IX_ADDR + 4
#define CTRL_FIFO_OUT_12_END_ADDR	CTRL_FIFO_OUT_12_WR_IX_ADDR + 4

#define CTRL_FIFO_IN_12_SIZE 		1024
#define CTRL_FIFO_IN_12_START_ADDR	0x40018408
#define CTRL_FIFO_IN_12_RD_IX_ADDR	CTRL_FIFO_IN_12_START_ADDR + CTRL_FIFO_IN_12_SIZE
#define CTRL_FIFO_IN_12_WR_IX_ADDR	CTRL_FIFO_IN_12_RD_IX_ADDR + 4
#define CTRL_FIFO_IN_12_END_ADDR	CTRL_FIFO_IN_12_WR_IX_ADDR + 4


// µB 13
#define CTRL_FIFO_OUT_13_SIZE 		1024
#define CTRL_FIFO_OUT_13_START_ADDR	0x4001a000
#define CTRL_FIFO_OUT_13_RD_IX_ADDR	CTRL_FIFO_OUT_13_START_ADDR + CTRL_FIFO_OUT_13_SIZE
#define CTRL_FIFO_OUT_13_WR_IX_ADDR	CTRL_FIFO_OUT_13_RD_IX_ADDR + 4
#define CTRL_FIFO_OUT_13_END_ADDR	CTRL_FIFO_OUT_13_WR_IX_ADDR + 4

#define CTRL_FIFO_IN_13_SIZE 		1024
#define CTRL_FIFO_IN_13_START_ADDR	0x4001a408
#define CTRL_FIFO_IN_13_RD_IX_ADDR	CTRL_FIFO_IN_13_START_ADDR + CTRL_FIFO_IN_13_SIZE
#define CTRL_FIFO_IN_13_WR_IX_ADDR	CTRL_FIFO_IN_13_RD_IX_ADDR + 4
#define CTRL_FIFO_IN_13_END_ADDR	CTRL_FIFO_IN_13_WR_IX_ADDR + 4


// µB 14
#define CTRL_FIFO_OUT_14_SIZE 		1024
#define CTRL_FIFO_OUT_14_START_ADDR	0x4001c000
#define CTRL_FIFO_OUT_14_RD_IX_ADDR	CTRL_FIFO_OUT_14_START_ADDR + CTRL_FIFO_OUT_14_SIZE
#define CTRL_FIFO_OUT_14_WR_IX_ADDR	CTRL_FIFO_OUT_14_RD_IX_ADDR + 4
#define CTRL_FIFO_OUT_14_END_ADDR	CTRL_FIFO_OUT_14_WR_IX_ADDR + 4

#define CTRL_FIFO_IN_14_SIZE 		1024
#define CTRL_FIFO_IN_14_START_ADDR	0x4001c408
#define CTRL_FIFO_IN_14_RD_IX_ADDR	CTRL_FIFO_IN_14_START_ADDR + CTRL_FIFO_IN_14_SIZE
#define CTRL_FIFO_IN_14_WR_IX_ADDR	CTRL_FIFO_IN_14_RD_IX_ADDR + 4
#define CTRL_FIFO_IN_14_END_ADDR	CTRL_FIFO_IN_14_WR_IX_ADDR + 4


// µB 15
#define CTRL_FIFO_OUT_15_SIZE 		1024
#define CTRL_FIFO_OUT_15_START_ADDR	0x4001e000
#define CTRL_FIFO_OUT_15_RD_IX_ADDR	CTRL_FIFO_OUT_15_START_ADDR + CTRL_FIFO_OUT_15_SIZE
#define CTRL_FIFO_OUT_15_WR_IX_ADDR	CTRL_FIFO_OUT_15_RD_IX_ADDR + 4
#define CTRL_FIFO_OUT_15_END_ADDR	CTRL_FIFO_OUT_15_WR_IX_ADDR + 4

#define CTRL_FIFO_IN_15_SIZE 		1024
#define CTRL_FIFO_IN_15_START_ADDR	0x4001e408
#define CTRL_FIFO_IN_15_RD_IX_ADDR	CTRL_FIFO_IN_15_START_ADDR + CTRL_FIFO_IN_15_SIZE
#define CTRL_FIFO_IN_15_WR_IX_ADDR	CTRL_FIFO_IN_15_RD_IX_ADDR + 4
#define CTRL_FIFO_IN_15_END_ADDR	CTRL_FIFO_IN_15_WR_IX_ADDR + 4


extern ctrl_fifo_hdlr ctrl_fifo_output[NB_PROCESSORS];		/* Control fifos*/
extern ctrl_fifo_hdlr ctrl_fifo_input[NB_PROCESSORS];
extern ctrl_fifo_hdlr input_data;							/* Fifo for input data */

void initCtrlFIFOs(){
	init_ctrl_fifo_hdlr(&ctrl_fifo_output[0], CTRL_FIFO_OUT_0_START_ADDR, CTRL_FIFO_OUT_0_RD_IX_ADDR, CTRL_FIFO_OUT_0_WR_IX_ADDR, CTRL_FIFO_OUT_0_SIZE);
//	init_ctrl_fifo_hdlr(&ctrl_fifo_input[0], 0x40000000, 0x4003D1E8, 0x4003D1EC, CTRL_FIFO_SIZE);
	init_ctrl_fifo_hdlr(&ctrl_fifo_input[0], CTRL_FIFO_IN_0_START_ADDR, CTRL_FIFO_IN_0_RD_IX_ADDR, CTRL_FIFO_IN_0_WR_IX_ADDR, CTRL_FIFO_IN_0_SIZE);

	init_ctrl_fifo_hdlr(&ctrl_fifo_output[1], CTRL_FIFO_OUT_1_START_ADDR, CTRL_FIFO_OUT_1_RD_IX_ADDR, CTRL_FIFO_OUT_1_WR_IX_ADDR, CTRL_FIFO_OUT_1_SIZE);
	init_ctrl_fifo_hdlr(&ctrl_fifo_input[1], CTRL_FIFO_IN_1_START_ADDR, CTRL_FIFO_IN_1_RD_IX_ADDR, CTRL_FIFO_IN_1_WR_IX_ADDR, CTRL_FIFO_IN_1_SIZE);

	init_ctrl_fifo_hdlr(&ctrl_fifo_output[2], CTRL_FIFO_OUT_2_START_ADDR, CTRL_FIFO_OUT_2_RD_IX_ADDR, CTRL_FIFO_OUT_2_WR_IX_ADDR, CTRL_FIFO_OUT_2_SIZE);
	init_ctrl_fifo_hdlr(&ctrl_fifo_input[2], CTRL_FIFO_IN_2_START_ADDR, CTRL_FIFO_IN_2_RD_IX_ADDR, CTRL_FIFO_IN_2_WR_IX_ADDR, CTRL_FIFO_IN_2_SIZE);

	init_ctrl_fifo_hdlr(&ctrl_fifo_output[3], CTRL_FIFO_OUT_3_START_ADDR, CTRL_FIFO_OUT_3_RD_IX_ADDR, CTRL_FIFO_OUT_3_WR_IX_ADDR, CTRL_FIFO_OUT_3_SIZE);
	init_ctrl_fifo_hdlr(&ctrl_fifo_input[3], CTRL_FIFO_IN_3_START_ADDR, CTRL_FIFO_IN_3_RD_IX_ADDR, CTRL_FIFO_IN_3_WR_IX_ADDR, CTRL_FIFO_IN_3_SIZE);

	init_ctrl_fifo_hdlr(&ctrl_fifo_output[4], CTRL_FIFO_OUT_4_START_ADDR, CTRL_FIFO_OUT_4_RD_IX_ADDR, CTRL_FIFO_OUT_4_WR_IX_ADDR, CTRL_FIFO_OUT_4_SIZE);
	init_ctrl_fifo_hdlr(&ctrl_fifo_input[4], CTRL_FIFO_IN_4_START_ADDR, CTRL_FIFO_IN_4_RD_IX_ADDR, CTRL_FIFO_IN_4_WR_IX_ADDR, CTRL_FIFO_IN_4_SIZE);

	init_ctrl_fifo_hdlr(&ctrl_fifo_output[5], CTRL_FIFO_OUT_5_START_ADDR, CTRL_FIFO_OUT_5_RD_IX_ADDR, CTRL_FIFO_OUT_5_WR_IX_ADDR, CTRL_FIFO_OUT_5_SIZE);
	init_ctrl_fifo_hdlr(&ctrl_fifo_input[5], CTRL_FIFO_IN_5_START_ADDR, CTRL_FIFO_IN_5_RD_IX_ADDR, CTRL_FIFO_IN_5_WR_IX_ADDR, CTRL_FIFO_IN_5_SIZE);

	init_ctrl_fifo_hdlr(&ctrl_fifo_output[6], CTRL_FIFO_OUT_6_START_ADDR, CTRL_FIFO_OUT_6_RD_IX_ADDR, CTRL_FIFO_OUT_6_WR_IX_ADDR, CTRL_FIFO_OUT_6_SIZE);
	init_ctrl_fifo_hdlr(&ctrl_fifo_input[6], CTRL_FIFO_IN_6_START_ADDR, CTRL_FIFO_IN_6_RD_IX_ADDR, CTRL_FIFO_IN_6_WR_IX_ADDR, CTRL_FIFO_IN_6_SIZE);

	init_ctrl_fifo_hdlr(&ctrl_fifo_output[7], CTRL_FIFO_OUT_7_START_ADDR, CTRL_FIFO_OUT_7_RD_IX_ADDR, CTRL_FIFO_OUT_7_WR_IX_ADDR, CTRL_FIFO_OUT_7_SIZE);
	init_ctrl_fifo_hdlr(&ctrl_fifo_input[7], CTRL_FIFO_IN_7_START_ADDR, CTRL_FIFO_IN_7_RD_IX_ADDR, CTRL_FIFO_IN_7_WR_IX_ADDR, CTRL_FIFO_IN_7_SIZE);

	init_ctrl_fifo_hdlr(&ctrl_fifo_output[8], CTRL_FIFO_OUT_8_START_ADDR, CTRL_FIFO_OUT_8_RD_IX_ADDR, CTRL_FIFO_OUT_8_WR_IX_ADDR, CTRL_FIFO_OUT_8_SIZE);
	init_ctrl_fifo_hdlr(&ctrl_fifo_input[8], CTRL_FIFO_IN_8_START_ADDR, CTRL_FIFO_IN_8_RD_IX_ADDR, CTRL_FIFO_IN_8_WR_IX_ADDR, CTRL_FIFO_IN_8_SIZE);

	init_ctrl_fifo_hdlr(&ctrl_fifo_output[9], CTRL_FIFO_OUT_9_START_ADDR, CTRL_FIFO_OUT_9_RD_IX_ADDR, CTRL_FIFO_OUT_9_WR_IX_ADDR, CTRL_FIFO_OUT_9_SIZE);
	init_ctrl_fifo_hdlr(&ctrl_fifo_input[9], CTRL_FIFO_IN_9_START_ADDR, CTRL_FIFO_IN_9_RD_IX_ADDR, CTRL_FIFO_IN_9_WR_IX_ADDR, CTRL_FIFO_IN_9_SIZE);

	init_ctrl_fifo_hdlr(&ctrl_fifo_output[10], CTRL_FIFO_OUT_10_START_ADDR, CTRL_FIFO_OUT_10_RD_IX_ADDR, CTRL_FIFO_OUT_10_WR_IX_ADDR, CTRL_FIFO_OUT_10_SIZE);
	init_ctrl_fifo_hdlr(&ctrl_fifo_input[10], CTRL_FIFO_IN_10_START_ADDR, CTRL_FIFO_IN_10_RD_IX_ADDR, CTRL_FIFO_IN_10_WR_IX_ADDR, CTRL_FIFO_IN_10_SIZE);

	init_ctrl_fifo_hdlr(&ctrl_fifo_output[11], CTRL_FIFO_OUT_11_START_ADDR, CTRL_FIFO_OUT_11_RD_IX_ADDR, CTRL_FIFO_OUT_11_WR_IX_ADDR, CTRL_FIFO_OUT_11_SIZE);
	init_ctrl_fifo_hdlr(&ctrl_fifo_input[11], CTRL_FIFO_IN_11_START_ADDR, CTRL_FIFO_IN_11_RD_IX_ADDR, CTRL_FIFO_IN_11_WR_IX_ADDR, CTRL_FIFO_IN_11_SIZE);

	init_ctrl_fifo_hdlr(&ctrl_fifo_output[12], CTRL_FIFO_OUT_12_START_ADDR, CTRL_FIFO_OUT_12_RD_IX_ADDR, CTRL_FIFO_OUT_12_WR_IX_ADDR, CTRL_FIFO_OUT_12_SIZE);
	init_ctrl_fifo_hdlr(&ctrl_fifo_input[12], CTRL_FIFO_IN_12_START_ADDR, CTRL_FIFO_IN_12_RD_IX_ADDR, CTRL_FIFO_IN_12_WR_IX_ADDR, CTRL_FIFO_IN_12_SIZE);

	init_ctrl_fifo_hdlr(&ctrl_fifo_output[13], CTRL_FIFO_OUT_13_START_ADDR, CTRL_FIFO_OUT_13_RD_IX_ADDR, CTRL_FIFO_OUT_13_WR_IX_ADDR, CTRL_FIFO_OUT_13_SIZE);
	init_ctrl_fifo_hdlr(&ctrl_fifo_input[13], CTRL_FIFO_IN_13_START_ADDR, CTRL_FIFO_IN_13_RD_IX_ADDR, CTRL_FIFO_IN_13_WR_IX_ADDR, CTRL_FIFO_IN_13_SIZE);

	init_ctrl_fifo_hdlr(&ctrl_fifo_output[14], CTRL_FIFO_OUT_14_START_ADDR, CTRL_FIFO_OUT_14_RD_IX_ADDR, CTRL_FIFO_OUT_14_WR_IX_ADDR, CTRL_FIFO_OUT_14_SIZE);
	init_ctrl_fifo_hdlr(&ctrl_fifo_input[14], CTRL_FIFO_IN_14_START_ADDR, CTRL_FIFO_IN_14_RD_IX_ADDR, CTRL_FIFO_IN_14_WR_IX_ADDR, CTRL_FIFO_IN_14_SIZE);

	init_ctrl_fifo_hdlr(&ctrl_fifo_output[15], CTRL_FIFO_OUT_15_START_ADDR, CTRL_FIFO_OUT_15_RD_IX_ADDR, CTRL_FIFO_OUT_15_WR_IX_ADDR, CTRL_FIFO_OUT_15_SIZE);
	init_ctrl_fifo_hdlr(&ctrl_fifo_input[15], CTRL_FIFO_IN_15_START_ADDR, CTRL_FIFO_IN_15_RD_IX_ADDR, CTRL_FIFO_IN_15_WR_IX_ADDR, CTRL_FIFO_IN_15_SIZE);

	// init video input fifo.
	init_ctrl_fifo_hdlr(&input_data, INPUT_FILE_START_ADDR, INPUT_FILE_RD_IX_ADDR, INPUT_FILE_WR_IX_ADDR, INPUT_FILE_SIZE);
}
